FROM node:23-slim AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY . .

RUN pnpm install --frozen-lockfile

RUN pnpm dash build

FROM steebchen/nginx-spa:stable

WORKDIR /app

COPY --from=builder /app/apps/dash/dist .

EXPOSE 80

CMD ["nginx"]
