FROM node:23-slim AS builder

WORKDIR /app

RUN npm install -g pnpm

COPY . .
RUN pnpm install --frozen-lockfile

RUN pnpm api build

FROM node:23-slim AS runtime

WORKDIR /usr/app

RUN npm install -g pnpm

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/api ./apps/api

EXPOSE 8081

CMD ["pnpm", "api", "start"]
