version: "3.9"

services:
  postgres:
    image: postgis/postgis
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cctech
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    restart: unless-stopped
    command: server /home/shared --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio:/data

volumes:
  postgres-data:
  minio:
  redis:
